name: digestabot

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

jobs:
  digestabot:
    name: Update image digests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
    steps:
      - uses: actions/checkout@v5
      - uses: navikt/digestabot@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: tilleggsstonader
